<?php

namespace Database\Seeders;

use App\Models\CourseOverview;
use Illuminate\Database\Seeder;

class CourseOverviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courseOverviews = [
            1 => [
                'Understand the foundational concepts of artificial intelligence',
                'Learn how intelligent agents operate in various environments',
                'Explore classical search algorithms and heuristics',
                'Understand logic-based reasoning and inference',
                'Analyze real-world AI applications across industries',
                'Build problem-solving frameworks using AI methods',
                'Introduction to probabilistic reasoning basics',
            ],
            2 => [
                'Understand supervised learning fundamentals',
                'Learn unsupervised learning and clustering techniques',
                'Explore model evaluation and validation methods',
                'Understand the workflow of building ML models',
                'Work with real datasets for hands-on ML practice',
                'Learn basic feature engineering techniques',
                'Understand principles behind regression and classification',
                'Introduction to bias and variance trade-offs',
            ],
            3 => [
                'Learn fundamental neural network architecture',
                'Understand activation functions and optimization methods',
                'Explore backpropagation and gradient descent',
                'Implement simple neural networks from scratch',
                'Understand overfitting and regularization techniques',
                'Work with real deep learning datasets (MNIST, etc.)',
                'Learn how deep learning powers modern AI applications',
                'Introduction to Convolutional Neural Networks (CNNs)',
            ],
            4 => [
                'Identify opportunities for AI automation in business',
                'Calculate ROI for AI implementation projects',
                'Understand ethical considerations in AI deployment',
                'Learn about predictive analytics for decision making',
                'Explore case studies of successful AI transformation',
                'Managing AI teams and technical stakeholders',
                'Future trends of AI in the corporate sector',
            ],
            5 => [
                'Understand the architecture of Large Language Models (LLMs)',
                'Master the art of zero-shot and few-shot prompting',
                'Learn chain-of-thought prompting techniques',
                'Use ChatGPT for coding, writing, and data analysis',
                'Identify hallucinations and limitations of LLMs',
                'Integrate ChatGPT workflows into daily productivity',
                'Advanced strategies for context management',
            ],
            6 => [
                'Understand the OSI and TCP/IP models in depth',
                'Learn the difference between routers, switches, and hubs',
                'Master IPv4 addressing and subnetting concepts',
                'Understand common protocols: DHCP, DNS, and HTTP',
                'Learn about cabling standards and network topologies',
                'Introduction to command line networking tools (ping, tracert)',
                'Basics of network performance metrics',
            ],
            7 => [
                'Configure VLANs and Trunking on Cisco switches',
                'Implement Inter-VLAN routing strategies',
                'Configure static and dynamic routing (OSPF)',
                'Implement Network Address Translation (NAT) and PAT',
                'Secure network devices using ACLs and port security',
                'Understand WAN technologies and VPN concepts',
                'Practice with Cisco Packet Tracer labs',
                'Troubleshoot common switching and routing issues',
            ],
            8 => [
                'Understand the CIA Triad (Confidentiality, Integrity, Availability)',
                'Learn about different types of firewalls and their placement',
                'Understand Intrusion Detection vs. Prevention Systems (IDS/IPS)',
                'Learn the basics of VPNs and secure tunneling',
                'Implement secure network architectures (DMZ)',
                'Understand wireless security standards (WPA2/WPA3)',
                'Basics of cryptography and encryption protocols',
            ],
            9 => [
                'Understand RF physics and wave propagation',
                'Learn about 802.11 standards (Wi-Fi 5, 6, 6E, 7)',
                'Design wireless LANs for coverage and capacity',
                'Configure Wireless Access Points and Controllers',
                'Troubleshoot wireless interference and signal issues',
                'Understand wireless security authentication methods',
                'Perform basic site surveys for deployment',
            ],
            10 => [
                'Master a structured approach to network troubleshooting',
                'Use protocol analyzers like Wireshark effectively',
                'Diagnose physical layer issues (cabling, interface errors)',
                'Troubleshoot connectivity issues with Ping and Traceroute',
                'Analyze DNS and DHCP failure scenarios',
                'Debug routing table inconsistencies',
                'Interpret system logs and SNMP traps',
            ],
            11 => [
                'Identify common cyber threats: malware, phishing, ransomware',
                'Understand the importance of password hygiene and MFA',
                'Learn basic social engineering defense mechanisms',
                'Explore the lifecycle of a cyber attack',
                'Understand data privacy regulations (GDPR, CCPA)',
                'Learn about endpoint security protection',
                'Introduction to incident response procedures',
            ],
            12 => [
                'Setup a virtualization lab with Kali Linux',
                'Understand the phases of ethical hacking (Recon, Scanning, etc.)',
                'Perform network scanning with Nmap',
                'Identify vulnerabilities using automated scanners',
                'Understand Metasploit framework basics',
                'Learn web application hacking basics (SQLi, XSS)',
                'Write a basic penetration testing report',
                'Understand legal and ethical boundaries',
            ],
            13 => [
                'Understand the chain of custody for digital evidence',
                'Learn how to image drives and preserve data integrity',
                'Analyze file systems and recover deleted files',
                'Investigate Windows registry for user activity',
                'Analyze email headers for tracing sources',
                'Use forensic tools like Autopsy and FTK Imager',
                'Document forensic findings for legal proceedings',
            ],
            14 => [
                'Understand the Shared Responsibility Model in cloud',
                'Learn Identity and Access Management (IAM) best practices',
                'Secure S3 buckets and cloud storage resources',
                'Implement cloud network security groups and NACLs',
                'Monitor cloud environments for suspicious activity',
                'Understand compliance standards in the cloud',
                'Introduction to Cloud Security Posture Management (CSPM)',
            ],
            15 => [
                'Define threat intelligence and its lifecycle',
                'Differentiate between tactical, operational, and strategic intel',
                'Learn to use Open Source Intelligence (OSINT) tools',
                'Analyze Indicators of Compromise (IoCs)',
                'Understand the MITRE ATT&CK framework',
                'Write actionable threat intelligence reports',
                'Map threat actors and their TTPs (Tactics, Techniques, Procedures)',
            ],
            16 => [
                'Define Cloud Computing: IaaS, PaaS, and SaaS',
                'Understand public, private, and hybrid cloud models',
                'Learn about virtualization technology (Hypervisors)',
                'Explore core cloud services: Compute, Storage, Networking',
                'Understand cloud scalability and elasticity concepts',
                'Analyze the cost benefits of cloud migration',
                'Introduction to serverless computing',
            ],
            17 => [
                'Design resilient architectures using AWS Global Infrastructure',
                'Master AWS VPC networking and security',
                'Understand EC2 instance types and auto-scaling',
                'Configure S3 storage classes and lifecycle policies',
                'Learn about database services (RDS, DynamoDB, Aurora)',
                'Implement High Availability and Fault Tolerance',
                'Understand decoupling applications with SQS and SNS',
                'Practice with exam-style scenario questions',
            ],
            18 => [
                'Navigate the Google Cloud Platform (GCP) Console',
                'Deploy applications using Google App Engine',
                'Manage virtual machines with Google Compute Engine',
                'Store data using Cloud Storage and Cloud SQL',
                'Understand Google Kubernetes Engine (GKE) basics',
                'Manage identity and access with Cloud IAM',
                'Monitor resources with Google Cloud Operations Suite',
            ],
            19 => [
                'Understand containerization concepts with Docker',
                'Learn Kubernetes architecture: Nodes, Pods, Clusters',
                'Deploy and manage applications using Deployments',
                'Configure Services for network exposure',
                'Manage configuration with ConfigMaps and Secrets',
                'Implement persistent storage with Volumes',
                'Learn basic Helm charts for package management',
                'Set up a CI/CD pipeline for Kubernetes',
            ],
            20 => [
                'Understand Infrastructure as Code (IaC) principles',
                'Install and configure Terraform providers',
                'Write Terraform configuration files (HCL)',
                'Manage state files and locking mechanisms',
                'Use modules to create reusable infrastructure code',
                'Plan and Apply infrastructure changes safely',
                'Manage variables and outputs effectively',
            ],
            21 => [
                'Introduction to the Data Science lifecycle',
                'Set up a Python environment with Anaconda/Jupyter',
                'Learn Python basics: variables, loops, functions',
                'Understand data types and structures in Python',
                'Introduction to NumPy for numerical computing',
                'Introduction to Pandas for data manipulation',
                'Basic data cleaning and preparation techniques',
            ],
            22 => [
                'Understand descriptive vs. inferential statistics',
                'Calculate mean, median, mode, and standard deviation',
                'Learn about probability distributions (Normal, Binomial)',
                'Understand correlation and causation',
                'Perform Hypothesis Testing (T-tests, P-values)',
                'Understand confidence intervals and sampling',
                'Apply statistical concepts to real-world datasets',
            ],
            23 => [
                'Connect to various data sources in Tableau',
                'Create basic charts: Bar, Line, Pie, and Scatter plots',
                'Use filters, groups, and sets to analyze data',
                'Create interactive dashboards and stories',
                'Implement calculated fields and parameters',
                'Map geographical data effectively',
                'Share and publish visualizations',
            ],
            24 => [
                'Master Pandas DataFrames and Series',
                'Perform data cleaning: handling missing values',
                'Merge, join, and concatenate datasets',
                'Group and aggregate data for insights',
                'Visualize data using Matplotlib and Seaborn',
                'Work with time-series data analysis',
                'Export processed data to various formats',
            ],
            25 => [
                'Implement Scikit-Learn pipelines for efficient workflows',
                'Tune hyperparameters using Grid Search and Random Search',
                'Handle imbalanced datasets effectively',
                'Implement Ensemble methods (Random Forest, Gradient Boosting)',
                'Understand Support Vector Machines (SVM) kernels',
                'Perform dimensionality reduction with PCA',
                'Deploy a simple ML model as an API',
                'Evaluate models using ROC curves and AUC',
            ],
            26 => [
                'Structure web pages using semantic HTML5 tags',
                'Work with forms, tables, and media elements',
                'Style elements using CSS selectors and properties',
                'Understand the Box Model (margin, padding, border)',
                'Create layouts using CSS Flexbox',
                'Create layouts using CSS Grid',
                'Implement responsive design with Media Queries',
            ],
            27 => [
                'Understand variables (let, const, var) and data types',
                'Write functions and arrow functions',
                'Manipulate the DOM (Document Object Model)',
                'Handle events (clicks, form submissions)',
                'Master Array methods (map, filter, reduce)',
                'Understand asynchronous JS (Promises, Async/Await)',
                'Fetch data from APIs using JSON',
            ],
            28 => [
                'Deep dive into React.js components and props',
                'Manage state with Hooks (useState, useEffect)',
                'Style applications with Tailwind CSS utility classes',
                'Handle routing with React Router',
                'Manage global state with Redux or Context API',
                'Optimize performance and lazy loading',
                'Deploy frontend applications to Vercel/Netlify',
                'Build a complete Single Page Application (SPA)',
            ],
            29 => [
                'Set up a Laravel development environment',
                'Understand MVC architecture in Laravel',
                'Define routes and controllers',
                'Interact with the database using Eloquent ORM',
                'Build RESTful APIs with resource controllers',
                'Implement authentication with Sanctum',
                'Validate request data effectively',
                'Write automated tests for your API',
            ],
            30 => [
                'Integrate a React frontend with a Laravel backend',
                'Handle CORS and API authentication flows',
                'Design a database schema for a complex app',
                'Implement file uploads and storage',
                'Build real-time features using WebSockets',
                'Deploy a full-stack application to a VPS',
                'Implement payment gateway integration (Stripe/Midtrans)',
                'Capstone project: Build a complete E-commerce site',
            ],
            31 => [
                'Navigate the Photoshop workspace and tools',
                'Understand layers, groups, and opacity',
                'Use selection tools (Lasso, Magic Wand, Marquee)',
                'Work with layer masks for non-destructive editing',
                'Basic color correction using Adjustment Layers',
                'Resize and crop images for different platforms',
                'Save and export files in correct formats',
            ],
            32 => [
                'Master the Pen Tool for precise cutouts',
                'Blend multiple images seamlessly',
                'Use Clone Stamp and Healing Brush for retouching',
                'Match lighting and perspective between images',
                'Create realistic shadows and reflections',
                'Apply filters and smart objects',
                'Create a surreal composition project',
            ],
            33 => [
                'Understand hierarchy and layout principles',
                'Work with typography and font pairing',
                'Use guides and grids for alignment',
                'Incorporate textures and blending modes',
                'Design a movie poster',
                'Design an event promotional poster',
                'Prepare files for print (CMYK vs RGB, Bleed)',
            ],
            34 => [
                'High-end skin retouching using Frequency Separation',
                'Dodge and Burn techniques for depth',
                'Advanced color grading with Curves',
                'Compositing complex scenes',
                'Automate workflows with Actions',
                'Focus stacking for sharp product photography',
                'Mastering RAW image processing',
            ],
            35 => [
                'Setup custom brushes and brush settings',
                'Understand graphic tablet pressure sensitivity',
                'Sketching and line art techniques',
                'Blocking in colors and values',
                'Painting light and shadow rendering',
                'Using blending modes for special effects',
                'Final polish and presentation of artwork',
            ],
            36 => [
                'Understand difference between Vector vs. Raster',
                'Master the Pen Tool and Bezier curves',
                'Use Shape tools and Pathfinder operations',
                'Work with strokes, fills, and gradients',
                'Organize artwork with layers and artboards',
                'Use the Type tool for text manipulation',
                'Export vectors for web (SVG) and print',
            ],
            37 => [
                'Understand the principles of effective logo design',
                'Brainstorming and sketching concepts',
                'Vectorizing sketches using Image Trace or Pen Tool',
                'Working with the Golden Ratio and grids',
                'Choosing appropriate color palettes',
                'Creating logo variations (lockups, icons)',
                'Preparing a logo delivery package',
            ],
            38 => [
                'Create flat design illustrations',
                'Use the Width Tool for dynamic strokes',
                'Create custom patterns and textures',
                'Use the Mesh Tool for realistic gradients',
                'Isometric illustration techniques',
                'Character design basics in vector',
                'Stylizing vector artwork for export',
            ],
            39 => [
                'Composition techniques for vector posters',
                'Creating vector halftones and effects',
                'Typography manipulation and custom lettering',
                'Using clipping masks for texture application',
                'Designing a vintage travel poster',
                'Designing a modern minimalist poster',
                'Pre-press checklist for vector posters',
            ],
            40 => [
                'Mastering the Gradient Mesh tool',
                'Creating complex 3D shapes with Revolve/Extrude',
                'Using Perspective Grid for architectural drawing',
                'Advanced pattern creation (seamless)',
                'Scripting and automation basics',
                'Data-driven graphics (variables)',
                'Interoperability with Photoshop and After Effects',
            ],
            41 => [
                'Navigate the Blender 3D viewport',
                'Understand Edit Mode vs. Object Mode',
                'Basic modeling tools: Extrude, Bevel, Loop Cut',
                'Apply basic materials and textures',
                'Setup basic 3-point lighting',
                'Configure the camera for rendering',
                'Render your first image with Eevee/Cycles',
            ],
            42 => [
                'Understand the animation timeline and keyframes',
                'Apply basic object transformations over time',
                'Use the Graph Editor for smooth motion',
                'Rigging a simple object with armatures',
                'Walk cycle animation basics',
                'Camera animation techniques',
                'Rendering an animation sequence to video',
            ],
            43 => [
                'Master sculpting brushes and settings',
                'Use Dyntopo for dynamic geometry',
                'Sculpting organic shapes (head/face)',
                'Retopology basics for clean mesh',
                'Baking normal maps from high-poly to low-poly',
                'Texture painting directly on the model',
                'Sculpting a creature or character',
            ],
            44 => [
                'Motion tracking footage in Blender',
                'Compositing 3D objects into real video',
                'Creating smoke and fire simulations',
                'Fluid simulation basics',
                'Particle systems for rain or debris',
                'Green screen keying in the compositor',
                'Render layers and passes',
            ],
            45 => [
                'Modeling low-poly assets for games',
                'UV Unwrapping techniques',
                'Texturing pipelines for game engines',
                'Optimization: Poly count and topology',
                'LOD (Level of Detail) creation',
                'Exporting to Unity/Unreal Engine (FBX/OBJ)',
                'Creating modular environment kits',
            ],
            46 => [
                'Understand the Color Wheel (Primary, Secondary, Tertiary)',
                'Learn about Hue, Saturation, and Value (HSV)',
                'Explore Warm vs. Cool colors',
                'Understand Color Harmonies (Complementary, Triadic)',
                'Psychological effects of different colors',
                'Accessibility and color contrast standards',
                'Creating your first color palette',
            ],
            47 => [
                'Understand the difference between Correction vs. Grading',
                'Reading Histograms and Scopes',
                'Creating specific moods (Cinematic, Vintage, bright)',
                'Split toning techniques',
                'Using LUTs (Look Up Tables) effectively',
                'Color grading workflow in Lightroom/Camera Raw',
                'Matching colors across a series of photos',
            ],
            48 => [
                'Using color to guide the viewer\'s eye',
                'Creating focal points with contrast',
                'Atmospheric perspective through color',
                'Balancing color weight in a composition',
                'Restricted color palettes for unity',
                'Analyzing famous artworks\' color usage',
                'Project: Repaint a scene with different moods',
            ],
            49 => [
                'Color psychology in marketing and sales',
                'Case studies of famous brand colors',
                'Defining a primary and secondary brand palette',
                'Color consistency across print and digital',
                'Cultural meanings of color in global markets',
                'Creating a brand style guide for color',
                'Testing color combinations for brand recognition',
            ],
            50 => [
                'Subconscious influence of color in UX design',
                'Color associations in different industries',
                'Testing color conversion rates (A/B testing)',
                'The physics of light and color perception',
                'Synesthesia and sensory color design',
                'Trends in color forecasting (Pantone Color of the Year)',
                'Advanced accessibility: Color blindness simulation',
            ],
            51 => [
                'Tour the Figma interface and tools',
                'Working with Frames vs. Groups',
                'Using Vector networks for icons',
                'Managing text and typography styles',
                'Importing images and masking',
                'Using plugins to speed up workflow',
                'Exporting assets for developers',
            ],
            52 => [
                'Connecting frames for navigation flow',
                'Setting up transition animations (Push, Slide, Fade)',
                'Using Smart Animate for complex interactions',
                'Creating overlays (modals, menus)',
                'Horizontal and vertical scrolling setup',
                'Sharing prototypes for user testing',
                'Using the Figma Mirror app',
            ],
            53 => [
                'Atomic Design methodology basics',
                'Creating reusable Components',
                'Using Variants and component properties',
                'Setting up Global Color and Text Styles',
                'Building a button library',
                'Managing a team library',
                'Documentation for design systems',
            ],
            54 => [
                'Understanding iOS Human Interface Guidelines',
                'Understanding Android Material Design',
                'Designing for touch targets and thumb zones',
                'Responsive constraints for different screen sizes',
                'Designing a mobile app navigation bar',
                'Creating a mobile onboarding flow',
                'Handoff process for mobile developers',
            ],
            55 => [
                'Mastering Auto Layout for responsive containers',
                'Advanced constraints and resizing logic',
                'Interactive components with state changes',
                'Micro-interactions using variables (if applicable)',
                'Building complex data tables',
                'Figma logic: variables and conditional prototyping',
                'integrating Figma with tools like Jira or Zeplin',
            ],
        ];

        foreach ($courseOverviews as $courseId => $descriptions) {
            foreach ($descriptions as $description) {
                CourseOverview::firstOrCreate([
                    'course_id'   => $courseId,
                    'description' => $description,
                ]);
            }
        }
    }
}