<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
       $courses = [
            [
                'name' => 'AI Fundamentals',
                'description' => 'Learn the foundations of artificial intelligence including search, logic, and agents.',
                'price' => 75000,
                'duration' => 120,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 3,
                'institute_id' => 7,
            ],
            [
                'name' => 'Machine Learning Basics',
                'description' => 'Understand supervised and unsupervised machine learning.',
                'price' => 95000,
                'duration' => 150,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 3,
                'institute_id' => 7,
            ],
            [
                'name' => 'Deep Learning Introduction',
                'description' => 'Learn neural networks and how they power modern AI.',
                'price' => 120000,
                'duration' => 180,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 3,
                'institute_id' => 7,
            ],
            [
                'name' => 'AI in Business',
                'description' => 'Use artificial intelligence for automation and analytics.',
                'price' => 85000,
                'duration' => 90,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 3,
                'institute_id' => 7,
            ],
            [
                'name' => 'ChatGPT Prompt Engineering',
                'description' => 'Learn how to write powerful prompts for LLMs.',
                'price' => 50000,
                'duration' => 60,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 3,
                'institute_id' => 7,
            ],
            [
                'name' => 'Networking Fundamentals',
                'description' => 'Learn IP, routing, switching, and core networking concepts.',
                'price' => 65000,
                'duration' => 100,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 4,
                'institute_id' => 8,
            ],
            [
                'name' => 'Cisco CCNA Prep',
                'description' => 'Prepare for the CCNA exam with hands-on routing labs.',
                'price' => 110000,
                'duration' => 180,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 4,
                'institute_id' => 8,
            ],
            [
                'name' => 'Network Security Basics',
                'description' => 'Understand firewalls, VPNs, and secure architectures.',
                'price' => 85000,
                'duration' => 120,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 4,
                'institute_id' => 8,
            ],
            [
                'name' => 'Wireless Networking',
                'description' => 'Learn WiFi architectures and optimization.',
                'price' => 50000,
                'duration' => 80,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 4,
                'institute_id' => 8,
            ],
            [
                'name' => 'Network Troubleshooting',
                'description' => 'Fix real-world networking problems using diagnostic tools.',
                'price' => 70000,
                'duration' => 100,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 4,
                'institute_id' => 8,
            ],
            [
                'name' => 'Cybersecurity Essentials',
                'description' => 'Learn basic cybersecurity concepts and threats.',
                'price' => 70000,
                'duration' => 100,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 5,
                'institute_id' => 8,
            ],
            [
                'name' => 'Ethical Hacking Introduction',
                'description' => 'Learn penetration testing and ethical hacking frameworks.',
                'price' => 120000,
                'duration' => 180,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 5,
                'institute_id' => 8,
            ],
            [
                'name' => 'Digital Forensics Basics',
                'description' => 'Learn how to retrieve data and analyze digital evidence.',
                'price' => 90000,
                'duration' => 140,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 5,
                'institute_id' => 8,
            ],
            [
                'name' => 'Cloud Security Fundamentals',
                'description' => 'Learn how to secure cloud-based infrastructure.',
                'price' => 95000,
                'duration' => 160,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 5,
                'institute_id' => 8,
            ],
            [
                'name' => 'Threat Intelligence Basics',
                'description' => 'Understand cyber threat analysis and reporting.',
                'price' => 60000,
                'duration' => 90,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 5,
                'institute_id' => 8,
            ],
            [
                'name' => 'Cloud Computing Fundamentals',
                'description' => 'Learn IaaS, PaaS, SaaS and cloud architectures.',
                'price' => 75000,
                'duration' => 120,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 6,
                'institute_id' => 10,
            ],
            [
                'name' => 'AWS Solutions Architect Prep',
                'description' => 'Study core AWS services & exam materials.',
                'price' => 150000,
                'duration' => 200,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 6,
                'institute_id' => 10,
            ],
            [
                'name' => 'Google Cloud Essentials',
                'description' => 'Learn GCP ecosystem and tools.',
                'price' => 90000,
                'duration' => 150,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 6,
                'institute_id' => 10,
            ],
            [
                'name' => 'DevOps with Kubernetes',
                'description' => 'Deploy and scale containerized applications.',
                'price' => 140000,
                'duration' => 180,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 6,
                'institute_id' => 10,
            ],
            [
                'name' => 'Cloud Automation with Terraform',
                'description' => 'Learn infrastructure as code (IaC).',
                'price' => 95000,
                'duration' => 120,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 6,
                'institute_id' => 10,
            ],
            [
                'name' => 'Data Science for Beginners',
                'description' => 'Learn Python, data processing, and visualization.',
                'price' => 80000,
                'duration' => 120,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 7,
                'institute_id' => 10,
            ],
            [
                'name' => 'Statistics for Data Science',
                'description' => 'Learn probability, distribution, and statistical testing.',
                'price' => 75000,
                'duration' => 100,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 7,
                'institute_id' => 10,
            ],
            [
                'name' => 'Data Visualization with Tableau',
                'description' => 'Build dashboards using Tableau.',
                'price' => 65000,
                'duration' => 80,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 7,
                'institute_id' => 10,
            ],
            [
                'name' => 'Python for Data Analysis',
                'description' => 'Use Pandas and NumPy for data manipulation.',
                'price' => 90000,
                'duration' => 130,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 7,
                'institute_id' => 10,
            ],
            [
                'name' => 'Machine Learning Intermediate',
                'description' => 'Build ML models with scikit-learn.',
                'price' => 110000,
                'duration' => 170,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 7,
                'institute_id' => 10,
            ],
            [
                'name' => 'HTML & CSS Basics',
                'description' => 'Learn website basics from scratch.',
                'price' => 50000,
                'duration' => 80,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 8,
                'institute_id' => 11,
            ],
            [
                'name' => 'JavaScript Essentials',
                'description' => 'Learn variables, functions, DOM, ES6.',
                'price' => 60000,
                'duration' => 90,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 8,
                'institute_id' => 11,
            ],
            [
                'name' => 'Frontend Developer Bootcamp',
                'description' => 'Master React, Tailwind, and modern frontend.',
                'price' => 150000,
                'duration' => 180,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 8,
                'institute_id' => 11,
            ],
            [
                'name' => 'Backend with Laravel',
                'description' => 'Build REST APIs using Laravel.',
                'price' => 130000,
                'duration' => 200,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 8,
                'institute_id' => 11,
            ],
            [
                'name' => 'Fullstack Developer Program',
                'description' => 'Become a fullstack engineer with real projects.',
                'price' => 200000,
                'duration' => 220,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 8,
                'institute_id' => 11,
            ],
            [
                'name' => 'Photoshop for Beginners',
                'description' => 'Learn the basics of Adobe Photoshop.',
                'price' => 55000,
                'duration' => 100,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 9,
                'institute_id' => 9,
            ],
            [
                'name' => 'Photo Manipulation Basics',
                'description' => 'Edit images with blending & retouching.',
                'price' => 70000,
                'duration' => 120,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 9,
                'institute_id' => 9,
            ],
            [
                'name' => 'Poster Design with Photoshop',
                'description' => 'Learn layout and typography.',
                'price' => 65000,
                'duration' => 100,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 9,
                'institute_id' => 9,
            ],
            [
                'name' => 'Advanced Photo Editing',
                'description' => 'Master advanced retouch techniques.',
                'price' => 90000,
                'duration' => 140,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 9,
                'institute_id' => 9,
            ],
            [
                'name' => 'Digital Painting in Photoshop',
                'description' => 'Learn digital art creation techniques.',
                'price' => 95000,
                'duration' => 160,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 9,
                'institute_id' => 9,
            ],
            [
                'name' => 'Adobe Illustrator Basics',
                'description' => 'Learn vector design fundamentals.',
                'price' => 60000,
                'duration' => 100,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 10,
                'institute_id' => 9,
            ],
            [
                'name' => 'Logo Design in Illustrator',
                'description' => 'Create logos using vector shapes.',
                'price' => 75000,
                'duration' => 120,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 10,
                'institute_id' => 9,
            ],
            [
                'name' => 'Illustration Techniques',
                'description' => 'Learn drawing tools & brushes.',
                'price' => 85000,
                'duration' => 140,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 10,
                'institute_id' => 9,
            ],
            [
                'name' => 'Poster Vector Art',
                'description' => 'Create vibrant vector posters.',
                'price' => 70000,
                'duration' => 100,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 10,
                'institute_id' => 9,
            ],
            [
                'name' => 'Advanced Illustrator Techniques',
                'description' => 'Learn mesh, blending, and complex shapes.',
                'price' => 90000,
                'duration' => 160,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 10,
                'institute_id' => 9,
            ],
            [
                'name' => 'Blender 3D Basics',
                'description' => 'Learn modeling, lighting, and rendering.',
                'price' => 80000,
                'duration' => 120,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 11,
                'institute_id' => 9,
            ],
            [
                'name' => '3D Animation in Blender',
                'description' => 'Learn animation workflows in 3D.',
                'price' => 95000,
                'duration' => 150,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 11,
                'institute_id' => 9,
            ],
            [
                'name' => 'Blender Sculpting Essentials',
                'description' => 'Sculpt realistic 3D characters.',
                'price' => 120000,
                'duration' => 180,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 11,
                'institute_id' => 9,
            ],
            [
                'name' => 'Blender VFX Basics',
                'description' => 'Create simple VFX scenes.',
                'price' => 90000,
                'duration' => 140,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 11,
                'institute_id' => 9,
            ],
            [
                'name' => 'Game Asset Creation',
                'description' => 'Create low-poly game assets.',
                'price' => 85000,
                'duration' => 120,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 11,
                'institute_id' => 9,
            ],
            [
                'name' => 'Color Theory Basics',
                'description' => 'Learn color psychology and design.',
                'price' => 55000,
                'duration' => 80,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 12,
                'institute_id' => 9,
            ],
            [
                'name' => 'Color Grading for Photos',
                'description' => 'Learn how to color grade images.',
                'price' => 65000,
                'duration' => 90,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 12,
                'institute_id' => 9,
            ],
            [
                'name' => 'Color Composition in Art',
                'description' => 'Learn how to use color in art and design.',
                'price' => 70000,
                'duration' => 100,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 12,
                'institute_id' => 9,
            ],
            [
                'name' => 'Color for Branding',
                'description' => 'Use color strategically in brand identity.',
                'price' => 80000,
                'duration' => 110,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 12,
                'institute_id' => 9,
            ],
            [
                'name' => 'Advanced Color Psychology',
                'description' => 'Explore advanced color theories in UX and marketing.',
                'price' => 85000,
                'duration' => 120,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 12,
                'institute_id' => 9,
            ],
            [
                'name' => 'Figma for Beginners',
                'description' => 'Learn the basics of UI design using Figma.',
                'price' => 60000,
                'duration' => 90,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 13,
                'institute_id' => 9,
            ],
            [
                'name' => 'Prototyping with Figma',
                'description' => 'Create interactive prototypes.',
                'price' => 70000,
                'duration' => 100,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 13,
                'institute_id' => 9,
            ],
            [
                'name' => 'Design Systems in Figma',
                'description' => 'Build scalable UI systems.',
                'price' => 95000,
                'duration' => 130,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 13,
                'institute_id' => 9,
            ],
            [
                'name' => 'Figma for Mobile Apps',
                'description' => 'Learn mobile UI design fundamentals.',
                'price' => 80000,
                'duration' => 110,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 13,
                'institute_id' => 9,
            ],
            [
                'name' => 'Advanced Figma Techniques',
                'description' => 'Master auto-layout, components, and animations.',
                'price' => 100000,
                'duration' => 140,
                'image' => 'http://127.0.0.1:8000/storage/course_images/R9Eypw1vCudEekwjoTqSgq3Ocqzj4Ibd61S6t2hZ.webp',
                'discount' => 0,
                'teacher_salary' => 10000,
                'category_id' => 13,
                'institute_id' => 9,
            ],
        ];

        foreach ($courses as $course) {
            Course::create($course);
        }
    }
}
