import { InstitutionData } from "@/interfaces/shared";


export const dummyInstitutions: InstitutionData[] = [
  {
    id: 1,
    name: "Tech Academy",
    logo: "tech-academy-logo.png",
    banner: "tech-academy-banner.jpg",
    description: "A leading institution in AI and data science education.",
    rating: 4.8,
    website: "",
    totalCourses: 15,
    totalTeachers: 5,
    category: "Technology",
    location: "Jakarta",
    contactEmail: "info@techacademy.com",
  },
  {
    id: 2,
    name: "DesignHub Academy",
    logo: "designhub-logo.png",
    banner: "designhub-banner.jpg",
    description: "A creative hub for modern designers and innovators.",
    rating: 4.7,
    website: "",
    totalCourses: 20,
    totalTeachers: 7,
    category: "Design",
    location: "Bandung",
    contactEmail: "hello@designhub.com",
  },
  {
    id: 3,
    name: "TechNet Academy",
    logo: "technet-logo.png",
    banner: "technet-banner.jpg",
    description: "Specialized in computer networking education.",
    rating: 4.6,
    website: "",
    totalCourses: 10,
    totalTeachers: 3,
    category: "Technology",
    location: "Surabaya",
    contactEmail: "contact@technet.com",
  },
  {
    id: 4,
    name: "CyberSafe Institute",
    logo: "cybersafe-logo.png",
    banner: "cybersafe-banner.jpg",
    description: "A professional institution for cyber security learning.",
    rating: 4.5,
    website: "",
    totalCourses: 8,
    totalTeachers: 4,
    category: "Technology",
    location: "Yogyakarta",
    contactEmail: "info@cybersafe.id",
  },
  {
    id: 5,
    name: "Cloud Academy Indonesia",
    logo: "cloudacademy-logo.png",
    banner: "cloudacademy-banner.jpg",
    description: "Training center for cloud technologies and certifications.",
    rating: 4.9,
    website: "",
    totalCourses: 12,
    totalTeachers: 6,
    category: "Technology",
    location: "Jakarta",
    contactEmail: "contact@cloudacademy.id",
  },
];
