import { TeacherRegisterProps } from "@/interfaces/shared";

export const dummyTeachers: TeacherRegisterProps[] = [
  {
    name: "Dr. John Doe",
    email: "john.doe@example.com",
    phone_number: "081234567890",
    password: "password123",
    password_confirmation: "password123",
    role_id: 2,
    description: "AI Expert with 10 years of experience",
    category: 3,
    graduates: [
      { id: 1, degree_title: "PhD in Computer Science", university_name: "MIT", degree_type: 1 },
      { id: 2, degree_title: "PhD in Computer Science", university_name: "MIT", degree_type: 1 },
    ],
    works: [
      { id: 1, duration: 60, institution: "OpenAI", position: "AI Researcher" },
      { id: 2, duration: 10, institution: "Google", position: "Full Stack Developer" },
    ],
    certificates: ["/images/certificate.jpg", "/images/certificate.jpg"],
  },
  {
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone_number: "082233445566",
    password: "securepass",
    password_confirmation: "securepass",
    role_id: 2,
    description: "Senior UI/UX Designer at Google",
    category: 11,
    graduates: [
      { id: 1, degree_title: "Bachelor of Design", university_name: "Stanford", degree_type: 1 },
    ],
    works: [
      { id: 1, duration: 48, institution: "Google", position: "Lead Designer" },
    ],
    certificates: [],
  },
  {
    name: "Ahmad Fauzi",
    email: "ahmad.fauzi@example.com",
    phone_number: "081212345678",
    password: "netpass123",
    password_confirmation: "netpass123",
    role_id: 2,
    description: "Network Engineer at Cisco",
    category: 4,
    graduates: [],
    works: [{ id: 1, duration: 36, institution: "Cisco", position: "Network Engineer" }],
    certificates: [],
  },
  {
    name: "Budi Santoso",
    email: "budi.santoso@example.com",
    phone_number: "081298765432",
    password: "cyber123",
    password_confirmation: "cyber123",
    role_id: 2,
    description: "Cyber Security Analyst at Telkom",
    category: 5,
    graduates: [],
    works: [{ id: 1, duration: 48, institution: "Telkom Indonesia", position: "Security Analyst" }],
    certificates: [],
  },
  {
    name: "Citra Lestari",
    email: "citra.lestari@example.com",
    phone_number: "081355566677",
    password: "cloud123",
    password_confirmation: "cloud123",
    role_id: 2,
    description: "Cloud Engineer at AWS",
    category: 6,
    graduates: [],
    works: [{ id: 1, duration: 24, institution: "AWS", position: "Cloud Engineer" }],
    certificates: [],
  },
];
